apiVersion: v1
kind: Service
metadata:
  name: {{ include "rungholtlegacy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rungholtlegacy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rungholtlegacy.selectorLabels" . | nindent 4 }}